export const STORE_BASE = "/loja/pizzaria-imperial";

export const routes = {
  preview: "/preview",
  store: {
    onboarding: `${STORE_BASE}/onboarding`,
    home: STORE_BASE,
    product: (id: string) => `${STORE_BASE}/produto/${id}`,
    cart: `${STORE_BASE}/carrinho`,
    cartEmpty: `${STORE_BASE}/carrinho/vazio`,
    identify: `${STORE_BASE}/identificacao`,
    identifyFilled: `${STORE_BASE}/identificacao/preenchido`,
    identifyError: `${STORE_BASE}/identificacao/erro`,
    identifyRecognized: `${STORE_BASE}/identificacao/reconhecido`,
    address: `${STORE_BASE}/endereco`,
    checkout: `${STORE_BASE}/checkout`,
    checkoutAddress: `${STORE_BASE}/checkout/endereco`,
    coupons: `${STORE_BASE}/cupons`,
    orders: `${STORE_BASE}/pedidos`,
    ordersEmpty: `${STORE_BASE}/pedidos/vazio`,
    order: (id: string) => `${STORE_BASE}/pedidos/${id}`,
    orderFull: (id: string) => `${STORE_BASE}/pedidos/${id}/completo`,
  },
  bio: "/bio/pizzaria-imperial",
  manager: {
    root: "/gestor/pizzaria-imperial",
    orders: "/gestor/pizzaria-imperial/pedidos",
    dispatch: "/gestor/pizzaria-imperial/expedicao",
    catalog: "/gestor/pizzaria-imperial/cardapio",
    history: "/gestor/pizzaria-imperial/historico",
    settings: "/gestor/pizzaria-imperial/configuracoes",
  },
  auth: {
    login: "/entrar",
    register: "/cadastro/restaurante",
    verifyEmail: "/verificar-email",
    forgot: "/esqueci-minha-senha",
    reset: "/redefinir-senha",
  },
  onboarding: {
    root: "/onboarding",
    company: "/onboarding/empresa",
    operation: "/onboarding/operacao",
    identity: "/onboarding/identidade",
    review: "/onboarding/revisao",
  },
  platform: {
    root: "/plataforma",
    stores: "/plataforma/estabelecimentos",
    store: (id: string) => `/plataforma/estabelecimentos/${id}`,
    admins: "/plataforma/administradores",
    audit: "/plataforma/auditoria",
    invite: (token: string) => `/plataforma/convites/${token}`,
  },
  managerFor: (slug: string) => ({
    root: `/gestor/${slug}`,
    orders: `/gestor/${slug}/pedidos`,
    dispatch: `/gestor/${slug}/expedicao`,
    catalog: `/gestor/${slug}/cardapio`,
    history: `/gestor/${slug}/historico`,
    settings: `/gestor/${slug}/configuracoes`,
  }),
  admin: {
    root: "/admin",
    performance: "/admin/desempenho",
    performanceMenu: "/admin/desempenho/cardapio",
    performanceCancellations: "/admin/desempenho/cancelamentos",
    orders: "/admin/pedidos",
    categories: "/admin/cardapio/categorias",
    products: "/admin/cardapio/produtos",
    productNew: "/admin/cardapio/produtos/novo",
    addons: "/admin/cardapio/complementos",
    coupons: "/admin/marketing/promocoes-cupons",
    coupon: (code: string) => `/admin/marketing/cupons/${code}`,
    tracking: "/admin/marketing/links-rastreamento",
    customers: "/admin/clientes",
    store: "/admin/configuracoes/loja",
    delivery: "/admin/configuracoes/entrega-pagamento",
  },
} as const;
